//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", ConfigurationName="SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_Out")]
    public interface SI_CARACT_LaborSafety_RFC01_Out {
        
        // CODEGEN: Generating message contract since the operation SI_CARACT_LaborSafety_RFC01_Out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutResponse SI_CARACT_LaborSafety_RFC01_Out(Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutResponse> SI_CARACT_LaborSafety_RFC01_OutAsync(Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT")]
    public partial class DT_CARACT_LaborSafety_RFC01Resquest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string caracteristicaField;
        
        private string valor_CaracteristicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Caracteristica {
            get {
                return this.caracteristicaField;
            }
            set {
                this.caracteristicaField = value;
                this.RaisePropertyChanged("Caracteristica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Valor_Caracteristica {
            get {
                return this.valor_CaracteristicaField;
            }
            set {
                this.valor_CaracteristicaField = value;
                this.RaisePropertyChanged("Valor_Caracteristica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT")]
    public partial class DT_CARACT_LaborSafety_RFC01_ResponseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string caracteristicaField;
        
        private string statusField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Caracteristica {
            get {
                return this.caracteristicaField;
            }
            set {
                this.caracteristicaField = value;
                this.RaisePropertyChanged("Caracteristica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CARACT_LaborSafety_RFC01_OutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Resquest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.DT_CARACT_LaborSafety_RFC01Resquest[] MT_CARACT_LaborSafety_RFC01;
        
        public SI_CARACT_LaborSafety_RFC01_OutRequest() {
        }
        
        public SI_CARACT_LaborSafety_RFC01_OutRequest(Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.DT_CARACT_LaborSafety_RFC01Resquest[] MT_CARACT_LaborSafety_RFC01) {
            this.MT_CARACT_LaborSafety_RFC01 = MT_CARACT_LaborSafety_RFC01;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CARACT_LaborSafety_RFC01_OutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.DT_CARACT_LaborSafety_RFC01_ResponseResponse[] MT_CARACT_LaborSafety_RFC01_Response;
        
        public SI_CARACT_LaborSafety_RFC01_OutResponse() {
        }
        
        public SI_CARACT_LaborSafety_RFC01_OutResponse(Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.DT_CARACT_LaborSafety_RFC01_ResponseResponse[] MT_CARACT_LaborSafety_RFC01_Response) {
            this.MT_CARACT_LaborSafety_RFC01_Response = MT_CARACT_LaborSafety_RFC01_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_CARACT_LaborSafety_RFC01_OutChannel : Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_CARACT_LaborSafety_RFC01_OutClient : System.ServiceModel.ClientBase<Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_Out>, Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_Out {
        
        public SI_CARACT_LaborSafety_RFC01_OutClient() {
        }
        
        public SI_CARACT_LaborSafety_RFC01_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_CARACT_LaborSafety_RFC01_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_CARACT_LaborSafety_RFC01_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_CARACT_LaborSafety_RFC01_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutResponse Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_Out.SI_CARACT_LaborSafety_RFC01_Out(Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutRequest request) {
            return base.Channel.SI_CARACT_LaborSafety_RFC01_Out(request);
        }
        
        public Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.DT_CARACT_LaborSafety_RFC01_ResponseResponse[] SI_CARACT_LaborSafety_RFC01_Out(Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.DT_CARACT_LaborSafety_RFC01Resquest[] MT_CARACT_LaborSafety_RFC01) {
            Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutRequest inValue = new Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutRequest();
            inValue.MT_CARACT_LaborSafety_RFC01 = MT_CARACT_LaborSafety_RFC01;
            Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutResponse retVal = ((Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_Out)(this)).SI_CARACT_LaborSafety_RFC01_Out(inValue);
            return retVal.MT_CARACT_LaborSafety_RFC01_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutResponse> Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_Out.SI_CARACT_LaborSafety_RFC01_OutAsync(Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutRequest request) {
            return base.Channel.SI_CARACT_LaborSafety_RFC01_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutResponse> SI_CARACT_LaborSafety_RFC01_OutAsync(Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.DT_CARACT_LaborSafety_RFC01Resquest[] MT_CARACT_LaborSafety_RFC01) {
            Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutRequest inValue = new Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_OutRequest();
            inValue.MT_CARACT_LaborSafety_RFC01 = MT_CARACT_LaborSafety_RFC01;
            return ((Ternium.LaborSafety.Integracao.SAP_01_DISCIPLINA_SERVICE.SI_CARACT_LaborSafety_RFC01_Out)(this)).SI_CARACT_LaborSafety_RFC01_OutAsync(inValue);
        }
    }
}
