//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", ConfigurationName="SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_Out")]
    public interface SI_ORDEMPM_LaborSafety_RFC05_Out {
        
        // CODEGEN: Generating message contract since the operation SI_ORDEMPM_LaborSafety_RFC05_Out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutResponse SI_ORDEMPM_LaborSafety_RFC05_Out(Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutResponse> SI_ORDEMPM_LaborSafety_RFC05_OutAsync(Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT")]
    public partial class DT_ORDEMPM_LaborSafety_RFC05Ordem_Pm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string num_OrdemField;
        
        private string desc_Ordem_ManutField;
        
        private string loc_InstalacaoField;
        
        private string operacaoField;
        
        private string desc_OperacaoField;
        
        private string centro_Trab_OpField;
        
        private string valor_Classe_OpField;
        
        private string chave_Mod_OpField;
        
        private string loc_Instalacao_OpField;
        
        private string status_OrdemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Num_Ordem {
            get {
                return this.num_OrdemField;
            }
            set {
                this.num_OrdemField = value;
                this.RaisePropertyChanged("Num_Ordem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Desc_Ordem_Manut {
            get {
                return this.desc_Ordem_ManutField;
            }
            set {
                this.desc_Ordem_ManutField = value;
                this.RaisePropertyChanged("Desc_Ordem_Manut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Loc_Instalacao {
            get {
                return this.loc_InstalacaoField;
            }
            set {
                this.loc_InstalacaoField = value;
                this.RaisePropertyChanged("Loc_Instalacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Operacao {
            get {
                return this.operacaoField;
            }
            set {
                this.operacaoField = value;
                this.RaisePropertyChanged("Operacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Desc_Operacao {
            get {
                return this.desc_OperacaoField;
            }
            set {
                this.desc_OperacaoField = value;
                this.RaisePropertyChanged("Desc_Operacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Centro_Trab_Op {
            get {
                return this.centro_Trab_OpField;
            }
            set {
                this.centro_Trab_OpField = value;
                this.RaisePropertyChanged("Centro_Trab_Op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Valor_Classe_Op {
            get {
                return this.valor_Classe_OpField;
            }
            set {
                this.valor_Classe_OpField = value;
                this.RaisePropertyChanged("Valor_Classe_Op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Chave_Mod_Op {
            get {
                return this.chave_Mod_OpField;
            }
            set {
                this.chave_Mod_OpField = value;
                this.RaisePropertyChanged("Chave_Mod_Op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Loc_Instalacao_Op {
            get {
                return this.loc_Instalacao_OpField;
            }
            set {
                this.loc_Instalacao_OpField = value;
                this.RaisePropertyChanged("Loc_Instalacao_Op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Status_Ordem {
            get {
                return this.status_OrdemField;
            }
            set {
                this.status_OrdemField = value;
                this.RaisePropertyChanged("Status_Ordem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT")]
    public partial class DT_ORDEMPM_LaborSafety_RFC05_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_ORDEMPM_LaborSafety_RFC05_ResponseResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_ORDEMPM_LaborSafety_RFC05_ResponseResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT")]
    public partial class DT_ORDEMPM_LaborSafety_RFC05_ResponseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vgrField;
        
        private string num_SerieField;
        
        private string end_RedeField;
        
        private string statusField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Vgr {
            get {
                return this.vgrField;
            }
            set {
                this.vgrField = value;
                this.RaisePropertyChanged("Vgr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Num_Serie {
            get {
                return this.num_SerieField;
            }
            set {
                this.num_SerieField = value;
                this.RaisePropertyChanged("Num_Serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string End_Rede {
            get {
                return this.end_RedeField;
            }
            set {
                this.end_RedeField = value;
                this.RaisePropertyChanged("End_Rede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ORDEMPM_LaborSafety_RFC05_OutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ordem_Pm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.DT_ORDEMPM_LaborSafety_RFC05Ordem_Pm[] MT_ORDEMPM_LaborSafety_RFC05;
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutRequest() {
        }
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutRequest(Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.DT_ORDEMPM_LaborSafety_RFC05Ordem_Pm[] MT_ORDEMPM_LaborSafety_RFC05) {
            this.MT_ORDEMPM_LaborSafety_RFC05 = MT_ORDEMPM_LaborSafety_RFC05;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ORDEMPM_LaborSafety_RFC05_OutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", Order=0)]
        public Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.DT_ORDEMPM_LaborSafety_RFC05_Response MT_ORDEMPM_LaborSafety_RFC05_Response;
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutResponse() {
        }
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutResponse(Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.DT_ORDEMPM_LaborSafety_RFC05_Response MT_ORDEMPM_LaborSafety_RFC05_Response) {
            this.MT_ORDEMPM_LaborSafety_RFC05_Response = MT_ORDEMPM_LaborSafety_RFC05_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ORDEMPM_LaborSafety_RFC05_OutChannel : Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ORDEMPM_LaborSafety_RFC05_OutClient : System.ServiceModel.ClientBase<Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_Out>, Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_Out {
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutClient() {
        }
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ORDEMPM_LaborSafety_RFC05_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutResponse Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_Out.SI_ORDEMPM_LaborSafety_RFC05_Out(Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutRequest request) {
            return base.Channel.SI_ORDEMPM_LaborSafety_RFC05_Out(request);
        }
        
        public Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.DT_ORDEMPM_LaborSafety_RFC05_Response SI_ORDEMPM_LaborSafety_RFC05_Out(Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.DT_ORDEMPM_LaborSafety_RFC05Ordem_Pm[] MT_ORDEMPM_LaborSafety_RFC05) {
            Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutRequest inValue = new Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutRequest();
            inValue.MT_ORDEMPM_LaborSafety_RFC05 = MT_ORDEMPM_LaborSafety_RFC05;
            Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutResponse retVal = ((Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_Out)(this)).SI_ORDEMPM_LaborSafety_RFC05_Out(inValue);
            return retVal.MT_ORDEMPM_LaborSafety_RFC05_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutResponse> Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_Out.SI_ORDEMPM_LaborSafety_RFC05_OutAsync(Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutRequest request) {
            return base.Channel.SI_ORDEMPM_LaborSafety_RFC05_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutResponse> SI_ORDEMPM_LaborSafety_RFC05_OutAsync(Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.DT_ORDEMPM_LaborSafety_RFC05Ordem_Pm[] MT_ORDEMPM_LaborSafety_RFC05) {
            Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutRequest inValue = new Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_OutRequest();
            inValue.MT_ORDEMPM_LaborSafety_RFC05 = MT_ORDEMPM_LaborSafety_RFC05;
            return ((Ternium.LaborSafety.Integracao.SAP_04_PERFIL_CATALOGO_SERVICE.SI_ORDEMPM_LaborSafety_RFC05_Out)(this)).SI_ORDEMPM_LaborSafety_RFC05_OutAsync(inValue);
        }
    }
}
