//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", ConfigurationName="SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_Out")]
    public interface SI_CHAVEMOD_LaborSafety_RFC02_Out {
        
        // CODEGEN: Generating message contract since the operation SI_CHAVEMOD_LaborSafety_RFC02_Out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutResponse SI_CHAVEMOD_LaborSafety_RFC02_Out(Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutResponse> SI_CHAVEMOD_LaborSafety_RFC02_OutAsync(Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT")]
    public partial class DT_CHAVEMOD_LaborSafety_RFC02Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chave_ModeloField;
        
        private string texto_Chave_ModeloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Chave_Modelo {
            get {
                return this.chave_ModeloField;
            }
            set {
                this.chave_ModeloField = value;
                this.RaisePropertyChanged("Chave_Modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Texto_Chave_Modelo {
            get {
                return this.texto_Chave_ModeloField;
            }
            set {
                this.texto_Chave_ModeloField = value;
                this.RaisePropertyChanged("Texto_Chave_Modelo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT")]
    public partial class DT_CHAVEMOD_LaborSafety_RFC02_ResponseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chave_ModeloField;
        
        private string statusField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Chave_Modelo {
            get {
                return this.chave_ModeloField;
            }
            set {
                this.chave_ModeloField = value;
                this.RaisePropertyChanged("Chave_Modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CHAVEMOD_LaborSafety_RFC02_OutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Request", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.DT_CHAVEMOD_LaborSafety_RFC02Request[] MT_CHAVEMOD_LaborSafety_RFC02;
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutRequest() {
        }
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutRequest(Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.DT_CHAVEMOD_LaborSafety_RFC02Request[] MT_CHAVEMOD_LaborSafety_RFC02) {
            this.MT_CHAVEMOD_LaborSafety_RFC02 = MT_CHAVEMOD_LaborSafety_RFC02;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CHAVEMOD_LaborSafety_RFC02_OutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ternium.com.br/INT_FromERP_toAPR_PT", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.DT_CHAVEMOD_LaborSafety_RFC02_ResponseResponse[] MT_CHAVEMOD_LaborSafety_RFC02_Response;
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutResponse() {
        }
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutResponse(Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.DT_CHAVEMOD_LaborSafety_RFC02_ResponseResponse[] MT_CHAVEMOD_LaborSafety_RFC02_Response) {
            this.MT_CHAVEMOD_LaborSafety_RFC02_Response = MT_CHAVEMOD_LaborSafety_RFC02_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_CHAVEMOD_LaborSafety_RFC02_OutChannel : Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_CHAVEMOD_LaborSafety_RFC02_OutClient : System.ServiceModel.ClientBase<Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_Out>, Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_Out {
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutClient() {
        }
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_CHAVEMOD_LaborSafety_RFC02_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutResponse Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_Out.SI_CHAVEMOD_LaborSafety_RFC02_Out(Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutRequest request) {
            return base.Channel.SI_CHAVEMOD_LaborSafety_RFC02_Out(request);
        }
        
        public Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.DT_CHAVEMOD_LaborSafety_RFC02_ResponseResponse[] SI_CHAVEMOD_LaborSafety_RFC02_Out(Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.DT_CHAVEMOD_LaborSafety_RFC02Request[] MT_CHAVEMOD_LaborSafety_RFC02) {
            Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutRequest inValue = new Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutRequest();
            inValue.MT_CHAVEMOD_LaborSafety_RFC02 = MT_CHAVEMOD_LaborSafety_RFC02;
            Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutResponse retVal = ((Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_Out)(this)).SI_CHAVEMOD_LaborSafety_RFC02_Out(inValue);
            return retVal.MT_CHAVEMOD_LaborSafety_RFC02_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutResponse> Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_Out.SI_CHAVEMOD_LaborSafety_RFC02_OutAsync(Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutRequest request) {
            return base.Channel.SI_CHAVEMOD_LaborSafety_RFC02_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutResponse> SI_CHAVEMOD_LaborSafety_RFC02_OutAsync(Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.DT_CHAVEMOD_LaborSafety_RFC02Request[] MT_CHAVEMOD_LaborSafety_RFC02) {
            Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutRequest inValue = new Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_OutRequest();
            inValue.MT_CHAVEMOD_LaborSafety_RFC02 = MT_CHAVEMOD_LaborSafety_RFC02;
            return ((Ternium.LaborSafety.Integracao.SAP_02_ATIVIDADE_PADRAO_SERVICE.SI_CHAVEMOD_LaborSafety_RFC02_Out)(this)).SI_CHAVEMOD_LaborSafety_RFC02_OutAsync(inValue);
        }
    }
}
