//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOQUEIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BLOQUEIO()
        {
            this.BLOQUEIO_LOCAL_INSTALACAO = new HashSet<BLOQUEIO_LOCAL_INSTALACAO>();
        }
    
        public long CodBloqueio { get; set; }
        public long CodLocalABloquear { get; set; }
        public long CodArea { get; set; }
        public long CodTagKKSBloqueio { get; set; }
        public long CodDispositivoBloqueio { get; set; }
        public long CodTipoEnergiaBloqueio { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual DISPOSITIVO_BLOQUEIO DISPOSITIVO_BLOQUEIO { get; set; }
        public virtual LOCAL_A_BLOQUEAR LOCAL_A_BLOQUEAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOQUEIO_LOCAL_INSTALACAO> BLOQUEIO_LOCAL_INSTALACAO { get; set; }
        public virtual TAG_KKS_BLOQUEIO TAG_KKS_BLOQUEIO { get; set; }
        public virtual TIPO_ENERGIA_BLOQUEIO TIPO_ENERGIA_BLOQUEIO { get; set; }
    }
}
