//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOQUEIO_LOCAL_INSTALACAO
    {
        public long CodBloqueioLocalInstalacao { get; set; }
        public long CodLocalInstalacao { get; set; }
        public long CodBloqueio { get; set; }
        public string CodigoBloqueio { get; set; }
    
        public virtual BLOQUEIO BLOQUEIO { get; set; }
        public virtual LOCAL_INSTALACAO LOCAL_INSTALACAO { get; set; }
    }
}
