//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_INDEXJOB_ANT
    {
        public string Database { get; set; }
        public System.DateTime Collect_Time { get; set; }
        public Nullable<short> database_id { get; set; }
        public Nullable<int> object_id { get; set; }
        public Nullable<int> index_id { get; set; }
        public string Schema { get; set; }
        public string Tabla { get; set; }
        public string Indice { get; set; }
        public Nullable<int> fill_factor { get; set; }
        public Nullable<int> partition_number { get; set; }
        public Nullable<long> page_count { get; set; }
        public Nullable<double> Current_AVG_Frag_Percent { get; set; }
        public string comando_exe { get; set; }
        public Nullable<System.DateTime> comando_inicio { get; set; }
        public Nullable<System.DateTime> comando_fin { get; set; }
        public string comando_msg { get; set; }
        public Nullable<System.DateTime> Collect_Time_Status { get; set; }
        public Nullable<double> POST_AVG_Frag_Percent { get; set; }
        public Nullable<double> Delta { get; set; }
    }
}
