//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_LaborSafetyEntities : DbContext
    {
        public DB_LaborSafetyEntities()
            : base("name=DB_LaborSafetyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMBIENTE> AMBIENTE { get; set; }
        public virtual DbSet<APR> APR { get; set; }
        public virtual DbSet<APROVADOR_APR> APROVADOR_APR { get; set; }
        public virtual DbSet<AREA> AREA { get; set; }
        public virtual DbSet<ATIVIDADE_PADRAO> ATIVIDADE_PADRAO { get; set; }
        public virtual DbSet<BLOQUEIO> BLOQUEIO { get; set; }
        public virtual DbSet<BLOQUEIO_LOCAL_INSTALACAO> BLOQUEIO_LOCAL_INSTALACAO { get; set; }
        public virtual DbSet<DISCIPLINA> DISCIPLINA { get; set; }
        public virtual DbSet<DISPOSITIVO_BLOQUEIO> DISPOSITIVO_BLOQUEIO { get; set; }
        public virtual DbSet<DURACAO> DURACAO { get; set; }
        public virtual DbSet<EPI> EPI { get; set; }
        public virtual DbSet<EPI_RISCO> EPI_RISCO { get; set; }
        public virtual DbSet<EPI_RISCO_INVENTARIO_AMBIENTE> EPI_RISCO_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<EPI_RISCO_INVENTARIO_ATIVIDADE> EPI_RISCO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<EPI_RISCO_RASCUNHO> EPI_RISCO_RASCUNHO { get; set; }
        public virtual DbSet<EPI_RISCO_RASCUNHO_INVENTARIO_AMBIENTE> EPI_RISCO_RASCUNHO_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<EPI_RISCO_RASCUNHO_INVENTARIO_ATIVIDADE> EPI_RISCO_RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<EXECUTANTE_APR> EXECUTANTE_APR { get; set; }
        public virtual DbSet<FUNCIONALIDADE> FUNCIONALIDADE { get; set; }
        public virtual DbSet<FUNCIONALIDADE_TELA> FUNCIONALIDADE_TELA { get; set; }
        public virtual DbSet<INVENTARIO_AMBIENTE> INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<INVENTARIO_ATIVIDADE> INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<LOCAL_A_BLOQUEAR> LOCAL_A_BLOQUEAR { get; set; }
        public virtual DbSet<LOCAL_INSTALACAO> LOCAL_INSTALACAO { get; set; }
        public virtual DbSet<LOCAL_INSTALACAO_INVENTARIO_AMBIENTE_HISTORICO_APR> LOCAL_INSTALACAO_INVENTARIO_AMBIENTE_HISTORICO_APR { get; set; }
        public virtual DbSet<LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE> LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE_HISTORICO_APR> LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE_HISTORICO_APR { get; set; }
        public virtual DbSet<LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE> LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<LOG_APR> LOG_APR { get; set; }
        public virtual DbSet<LOG_INVENTARIO_AMBIENTE> LOG_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<LOG_INVENTARIO_ATIVIDADE> LOG_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<LOG_OPERACAO_APR> LOG_OPERACAO_APR { get; set; }
        public virtual DbSet<LOG_PERFIL_FUNCIONALIDADE> LOG_PERFIL_FUNCIONALIDADE { get; set; }
        public virtual DbSet<LOG_RISCO_INVENTARIO_AMBIENTE> LOG_RISCO_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<LOG_RISCO_INVENTARIO_ATIVIDADE> LOG_RISCO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<LOG_TIPO_OPERACAO> LOG_TIPO_OPERACAO { get; set; }
        public virtual DbSet<NR> NR { get; set; }
        public virtual DbSet<NR_INVENTARIO_AMBIENTE> NR_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<NR_RASCUNHO_INVENTARIO_AMBIENTE> NR_RASCUNHO_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<OPERACAO_APR> OPERACAO_APR { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERFIL_CATALOGO> PERFIL_CATALOGO { get; set; }
        public virtual DbSet<PERFIL_FUNCIONALIDADE> PERFIL_FUNCIONALIDADE { get; set; }
        public virtual DbSet<PESO> PESO { get; set; }
        public virtual DbSet<PESSOA> PESSOA { get; set; }
        public virtual DbSet<PROBABILIDADE> PROBABILIDADE { get; set; }
        public virtual DbSet<RASCUNHO_INVENTARIO_AMBIENTE> RASCUNHO_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<RASCUNHO_INVENTARIO_ATIVIDADE> RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<RESPONSAVEL_INVENTARIO_AMBIENTE> RESPONSAVEL_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<RESPONSAVEL_INVENTARIO_ATIVIDADE> RESPONSAVEL_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<RISCO> RISCO { get; set; }
        public virtual DbSet<RISCO_APR> RISCO_APR { get; set; }
        public virtual DbSet<RISCO_INVENTARIO_AMBIENTE> RISCO_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<RISCO_INVENTARIO_ATIVIDADE> RISCO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<RISCO_RASCUNHO_INVENTARIO_AMBIENTE> RISCO_RASCUNHO_INVENTARIO_AMBIENTE { get; set; }
        public virtual DbSet<RISCO_RASCUNHO_INVENTARIO_ATIVIDADE> RISCO_RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual DbSet<SEVERIDADE> SEVERIDADE { get; set; }
        public virtual DbSet<STATUS_APR> STATUS_APR { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TAG_KKS_BLOQUEIO> TAG_KKS_BLOQUEIO { get; set; }
        public virtual DbSet<TELA> TELA { get; set; }
        public virtual DbSet<TIPO_ENERGIA_BLOQUEIO> TIPO_ENERGIA_BLOQUEIO { get; set; }
        public virtual DbSet<TIPO_RISCO> TIPO_RISCO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
        public virtual DbSet<DBA_INDEXJOB> DBA_INDEXJOB { get; set; }
        public virtual DbSet<DBA_INDEXJOB_ANT> DBA_INDEXJOB_ANT { get; set; }
    }
}
