//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPI_RISCO_INVENTARIO_AMBIENTE
    {
        public long CodEpiRiscoInventarioAmbiente { get; set; }
        public long CodEPI { get; set; }
        public long CodRiscoInventarioAmbiente { get; set; }
    
        public virtual EPI EPI { get; set; }
        public virtual RISCO_INVENTARIO_AMBIENTE RISCO_INVENTARIO_AMBIENTE { get; set; }
    }
}
