//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPI_RISCO_RASCUNHO_INVENTARIO_ATIVIDADE
    {
        public long CodEpiRiscoRascunhoInventarioAtividade { get; set; }
        public long CodEPI { get; set; }
        public long CodRiscoRascunhoInventarioAtividade { get; set; }
    
        public virtual EPI EPI { get; set; }
        public virtual RISCO_RASCUNHO_INVENTARIO_ATIVIDADE RISCO_RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
    }
}
