//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_AMBIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO_AMBIENTE()
        {
            this.LOCAL_INSTALACAO = new HashSet<LOCAL_INSTALACAO>();
            this.NR_INVENTARIO_AMBIENTE = new HashSet<NR_INVENTARIO_AMBIENTE>();
            this.RISCO_INVENTARIO_AMBIENTE = new HashSet<RISCO_INVENTARIO_AMBIENTE>();
        }
    
        public long CodInventarioAmbiente { get; set; }
        public string Codigo { get; set; }
        public long CodAmbiente { get; set; }
        public string Descricao { get; set; }
        public string ObservacaoGeral { get; set; }
        public int RiscoGeral { get; set; }
        public System.DateTime DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual AMBIENTE AMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCAL_INSTALACAO> LOCAL_INSTALACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NR_INVENTARIO_AMBIENTE> NR_INVENTARIO_AMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_INVENTARIO_AMBIENTE> RISCO_INVENTARIO_AMBIENTE { get; set; }
    }
}
