//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_ATIVIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO_ATIVIDADE()
        {
            this.LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE = new HashSet<LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE>();
            this.RESPONSAVEL_INVENTARIO_ATIVIDADE = new HashSet<RESPONSAVEL_INVENTARIO_ATIVIDADE>();
            this.RISCO_INVENTARIO_ATIVIDADE = new HashSet<RISCO_INVENTARIO_ATIVIDADE>();
        }
    
        public long CodInventarioAtividade { get; set; }
        public string Codigo { get; set; }
        public long CodPeso { get; set; }
        public long CodPerfilCatalogo { get; set; }
        public long CodDuracao { get; set; }
        public long CodAtividade { get; set; }
        public long CodDisciplina { get; set; }
        public string Descricao { get; set; }
        public int RiscoGeral { get; set; }
        public string ObservacaoGeral { get; set; }
        public System.DateTime DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ATIVIDADE_PADRAO ATIVIDADE_PADRAO { get; set; }
        public virtual DISCIPLINA DISCIPLINA { get; set; }
        public virtual DURACAO DURACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE> LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPONSAVEL_INVENTARIO_ATIVIDADE> RESPONSAVEL_INVENTARIO_ATIVIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_INVENTARIO_ATIVIDADE> RISCO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual PERFIL_CATALOGO PERFIL_CATALOGO { get; set; }
        public virtual PESO PESO { get; set; }
    }
}
