//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCAL_INSTALACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCAL_INSTALACAO()
        {
            this.BLOQUEIO_LOCAL_INSTALACAO = new HashSet<BLOQUEIO_LOCAL_INSTALACAO>();
            this.LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE = new HashSet<LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE>();
            this.LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE = new HashSet<LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE>();
        }
    
        public long CodLocalInstalacao { get; set; }
        public long CodInventarioAmbiente { get; set; }
        public long CodPeso { get; set; }
        public long CodPerfilCatalogo { get; set; }
        public string N1 { get; set; }
        public string N2 { get; set; }
        public string N3 { get; set; }
        public string N4 { get; set; }
        public string N5 { get; set; }
        public string N6 { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOQUEIO_LOCAL_INSTALACAO> BLOQUEIO_LOCAL_INSTALACAO { get; set; }
        public virtual INVENTARIO_AMBIENTE INVENTARIO_AMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE> LOCAL_INSTALACAO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual PERFIL_CATALOGO PERFIL_CATALOGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE> LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual PESO PESO { get; set; }
    }
}
