//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_PERFIL_FUNCIONALIDADE
    {
        public long CodLogPerfilFuncionalidade { get; set; }
        public string CodUsuarioModificador { get; set; }
        public long CodPerfil { get; set; }
        public long CodTela { get; set; }
        public string CodigosFuncionalidadesAnteriores { get; set; }
        public string CodigosNovasFuncionalidades { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    }
}
