//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_INVENTARIO_AMBIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOG_INVENTARIO_AMBIENTE()
        {
            this.LOG_RISCO_INVENTARIO_AMBIENTE = new HashSet<LOG_RISCO_INVENTARIO_AMBIENTE>();
        }
    
        public long CodLogInventarioAmbiente { get; set; }
        public long CodLogTipoOperacao { get; set; }
        public string CodInventariosAntigos { get; set; }
        public long CodInventario { get; set; }
        public string CodUsuarioModificador { get; set; }
        public Nullable<long> CodAmbienteAntigo { get; set; }
        public Nullable<long> CodAmbienteNovo { get; set; }
        public string DescricaoAntiga { get; set; }
        public string DescricaoNova { get; set; }
        public string CodigosNRsAntigas { get; set; }
        public string CodigosNRsNovas { get; set; }
        public string ObsGeralAntiga { get; set; }
        public string ObsGeralNova { get; set; }
        public string CodigosLIsAntigos { get; set; }
        public string CodigosLIsNovos { get; set; }
        public Nullable<long> RiscoGeralAntigo { get; set; }
        public Nullable<long> RiscoGeralNovo { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual LOG_TIPO_OPERACAO LOG_TIPO_OPERACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_RISCO_INVENTARIO_AMBIENTE> LOG_RISCO_INVENTARIO_AMBIENTE { get; set; }
    }
}
