//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class NR_RASCUNHO_INVENTARIO_AMBIENTE
    {
        public long CodNRRascunhoInventarioAmbiente { get; set; }
        public long CodRascunhoInventarioAmbiente { get; set; }
        public long CodNR { get; set; }
    
        public virtual NR NR { get; set; }
        public virtual RASCUNHO_INVENTARIO_AMBIENTE RASCUNHO_INVENTARIO_AMBIENTE { get; set; }
    }
}
