//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_CATALOGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERFIL_CATALOGO()
        {
            this.INVENTARIO_ATIVIDADE = new HashSet<INVENTARIO_ATIVIDADE>();
            this.LOCAL_INSTALACAO = new HashSet<LOCAL_INSTALACAO>();
        }
    
        public long CodPerfilCatalogo { get; set; }
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public string Idioma { get; set; }
        public int Mdt { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO_ATIVIDADE> INVENTARIO_ATIVIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCAL_INSTALACAO> LOCAL_INSTALACAO { get; set; }
    }
}
