//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_FUNCIONALIDADE
    {
        public long CodPerfilFuncionalidade { get; set; }
        public long CodPerfil { get; set; }
        public long CodFuncionalidade { get; set; }
        public bool Edicao { get; set; }
        public long CodTela { get; set; }
    
        public virtual FUNCIONALIDADE FUNCIONALIDADE { get; set; }
        public virtual PERFIL PERFIL { get; set; }
        public virtual TELA TELA { get; set; }
    }
}
