//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RASCUNHO_INVENTARIO_ATIVIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RASCUNHO_INVENTARIO_ATIVIDADE()
        {
            this.LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE = new HashSet<LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE>();
            this.RISCO_RASCUNHO_INVENTARIO_ATIVIDADE = new HashSet<RISCO_RASCUNHO_INVENTARIO_ATIVIDADE>();
        }
    
        public long CodRascunhoInventarioAtividade { get; set; }
        public string Codigo { get; set; }
        public Nullable<long> CodPeso { get; set; }
        public Nullable<long> CodPerfilCatalogo { get; set; }
        public Nullable<long> CodDuracao { get; set; }
        public Nullable<long> CodAtividade { get; set; }
        public Nullable<long> CodDisciplina { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> RiscoGeral { get; set; }
        public string ObservacaoGeral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE> LOCAL_INSTALACAO_RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_RASCUNHO_INVENTARIO_ATIVIDADE> RISCO_RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
    }
}
