//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPONSAVEL_INVENTARIO_AMBIENTE
    {
        public long CodResponsavelInventarioAmbiente { get; set; }
        public long CodInventarioAmbiente { get; set; }
        public long CodUsuario { get; set; }
    }
}
