//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISCO_INVENTARIO_AMBIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RISCO_INVENTARIO_AMBIENTE()
        {
            this.EPI_RISCO_INVENTARIO_AMBIENTE = new HashSet<EPI_RISCO_INVENTARIO_AMBIENTE>();
        }
    
        public long CodRiscoInventarioAmbiente { get; set; }
        public long CodInventarioAmbiente { get; set; }
        public long CodRiscoAmbiente { get; set; }
        public long CodSeveridade { get; set; }
        public long CodProbabilidade { get; set; }
        public string FonteGeradora { get; set; }
        public string ProcedimentosAplicaveis { get; set; }
        public string ContraMedidas { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPI_RISCO_INVENTARIO_AMBIENTE> EPI_RISCO_INVENTARIO_AMBIENTE { get; set; }
        public virtual INVENTARIO_AMBIENTE INVENTARIO_AMBIENTE { get; set; }
        public virtual PROBABILIDADE PROBABILIDADE { get; set; }
        public virtual RISCO RISCO { get; set; }
        public virtual SEVERIDADE SEVERIDADE { get; set; }
    }
}
