//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RISCO()
        {
            this.EPI_RISCO = new HashSet<EPI_RISCO>();
            this.EPI_RISCO_RASCUNHO = new HashSet<EPI_RISCO_RASCUNHO>();
            this.RISCO_APR = new HashSet<RISCO_APR>();
            this.RISCO_RASCUNHO_INVENTARIO_AMBIENTE = new HashSet<RISCO_RASCUNHO_INVENTARIO_AMBIENTE>();
            this.RISCO_RASCUNHO_INVENTARIO_ATIVIDADE = new HashSet<RISCO_RASCUNHO_INVENTARIO_ATIVIDADE>();
            this.RISCO_INVENTARIO_AMBIENTE = new HashSet<RISCO_INVENTARIO_AMBIENTE>();
            this.RISCO_INVENTARIO_ATIVIDADE = new HashSet<RISCO_INVENTARIO_ATIVIDADE>();
        }
    
        public long CodRisco { get; set; }
        public long CodTipoRisco { get; set; }
        public string Nome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPI_RISCO> EPI_RISCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPI_RISCO_RASCUNHO> EPI_RISCO_RASCUNHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_APR> RISCO_APR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_RASCUNHO_INVENTARIO_AMBIENTE> RISCO_RASCUNHO_INVENTARIO_AMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_RASCUNHO_INVENTARIO_ATIVIDADE> RISCO_RASCUNHO_INVENTARIO_ATIVIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_INVENTARIO_AMBIENTE> RISCO_INVENTARIO_AMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_INVENTARIO_ATIVIDADE> RISCO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual TIPO_RISCO TIPO_RISCO { get; set; }
    }
}
