//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISCO_INVENTARIO_ATIVIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RISCO_INVENTARIO_ATIVIDADE()
        {
            this.EPI_RISCO_INVENTARIO_ATIVIDADE = new HashSet<EPI_RISCO_INVENTARIO_ATIVIDADE>();
        }
    
        public long CodRiscoInventarioAtividade { get; set; }
        public long CodRisco { get; set; }
        public long CodInventarioAtividade { get; set; }
        public long CodSeveridade { get; set; }
        public string FonteGeradora { get; set; }
        public string ProcedimentoAplicavel { get; set; }
        public string ContraMedidas { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPI_RISCO_INVENTARIO_ATIVIDADE> EPI_RISCO_INVENTARIO_ATIVIDADE { get; set; }
        public virtual INVENTARIO_ATIVIDADE INVENTARIO_ATIVIDADE { get; set; }
        public virtual RISCO RISCO { get; set; }
        public virtual SEVERIDADE SEVERIDADE { get; set; }
    }
}
