//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEVERIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEVERIDADE()
        {
            this.RISCO_INVENTARIO_AMBIENTE = new HashSet<RISCO_INVENTARIO_AMBIENTE>();
            this.RISCO_INVENTARIO_ATIVIDADE = new HashSet<RISCO_INVENTARIO_ATIVIDADE>();
        }
    
        public long CodSeveridade { get; set; }
        public decimal Indice { get; set; }
        public string Nome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_INVENTARIO_AMBIENTE> RISCO_INVENTARIO_AMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISCO_INVENTARIO_ATIVIDADE> RISCO_INVENTARIO_ATIVIDADE { get; set; }
    }
}
