//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborSafety.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PERFIL
    {
        public long CodUsuarioPerfil { get; set; }
        public long CodUsuario { get; set; }
        public long CodPerfil { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
